---
title: "Results"
output: 
  html_document: 
    keep_md: yes
    toc: true
---

```{r}
library(tidyverse)
library(ggplot2)
```

# A1 

```{r, echo=FALSE, fig.width=12, fig.height=8, results='hide'}
res = lapply(1:3, function(i) readRDS(paste0("results/a_1_sp_",i,"_.RDS")))
data =
  lapply(1:3, function(i) {
  df = as.data.frame(do.call(rbind, asplit(res[[i]], 1)))
  df$algorithm = c("MAR", "BRT", "RF", "Random", "Zero")
  df$iter = sort(rep(1:20, 5))
  data = df %>% pivot_longer(cols = c(rmse_p, rmse_b, correlation_p, correlation_b))
  data$species = c(5, 10, 20)[i]
  data$type = rep(c("Count", "Presence/absence"), 200)
  return(data)
})
data = do.call(rbind, data)
data = data %>% 
  mutate(species=as.factor(species), 
         algorithm=as.factor(algorithm))

data$name = fct_collapse(data$name, 
                         spearman = c("correlation_p", "correlation_b"),
                         'log(rmse)' = c("rmse_p", "rmse_b"))

data$value[data$name == "log(rmse)"] = log(data$value[data$name == "log(rmse)"]+1)

data %>% 
  ggplot(aes(x = reorder(algorithm,rep(1:5, 240), na.rm=TRUE), y = value, fill=species)) +
  geom_boxplot() +
  theme_bw() + 
  labs(x = "Algorithm") +
  facet_grid(name~type, scale="free") +
     theme(
      plot.tag = element_text(size = 12),
      plot.title = element_text(size = 13, hjust = 0.1 , margin = margin(t = 10, b = -20)),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 8),
      strip.text = element_text(size = 12),
      strip.background = element_rect(color = NA))
```


# A2 

```{r, echo=FALSE, fig.width=12, fig.height=8, results='hide'}
res = lapply(1:3, function(i) readRDS(paste0("results/a_2_sp_",i,"_.RDS")))
data =
  lapply(1:3, function(i) {
  df = as.data.frame(do.call(rbind, asplit(res[[i]], 1)))
  df$algorithm = c("MAR", "BRT", "RF", "Random", "Zero")
  df$iter = sort(rep(1:20, 5))
  data = df %>% pivot_longer(cols = c(rmse_p, rmse_b, correlation_p, correlation_b))
  data$species = c(5, 10, 20)[i]
  data$type = rep(c("Count", "Presence/absence"), 200)
  return(data)
})
data = do.call(rbind, data)
data = data %>% 
  mutate(species=as.factor(species), 
         algorithm=as.factor(algorithm))

data$name = fct_collapse(data$name, 
                         spearman = c("correlation_p", "correlation_b"),
                         'log(rmse)' = c("rmse_p", "rmse_b"))

data$value[data$name == "log(rmse)"] = log(data$value[data$name == "log(rmse)"]+1)

data %>% 
  ggplot(aes(x = reorder(algorithm,rep(1:5, 240), na.rm=TRUE), y = value, fill=species)) +
  geom_boxplot() +
  theme_bw() + 
  labs(x = "Algorithm") +
  facet_grid(name~type, scale="free") +
     theme(
      plot.tag = element_text(size = 12),
      plot.title = element_text(size = 13, hjust = 0.1 , margin = margin(t = 10, b = -20)),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 8),
      strip.text = element_text(size = 12),
      strip.background = element_rect(color = NA))
```


# A3 

```{r, echo=FALSE, fig.width=12, fig.height=8, results='hide'}
res = lapply(1:3, function(i) readRDS(paste0("results/a_3_sp_",i,"_.RDS")))
data =
  lapply(1:3, function(i) {
  df = as.data.frame(do.call(rbind, asplit(res[[i]], 1)))
  df$algorithm = c("MAR", "BRT", "RF", "Random", "Zero")
  df$iter = sort(rep(1:20, 5))
  data = df %>% pivot_longer(cols = c(rmse_p, rmse_b, correlation_p, correlation_b))
  data$species = c(5, 10, 20)[i]
  data$type = rep(c("Count", "Presence/absence"), 200)
  return(data)
})
data = do.call(rbind, data)
data = data %>% 
  mutate(species=as.factor(species), 
         algorithm=as.factor(algorithm))

data$name = fct_collapse(data$name, 
                         spearman = c("correlation_p", "correlation_b"),
                         'log(rmse)' = c("rmse_p", "rmse_b"))

data$value[data$name == "log(rmse)"] = log(data$value[data$name == "log(rmse)"]+1)

data %>% 
  ggplot(aes(x = reorder(algorithm,rep(1:5, 240), na.rm=TRUE), y = value, fill=species)) +
  geom_boxplot() +
  theme_bw() + 
  labs(x = "Algorithm") +
  facet_grid(name~type, scale="free") +
     theme(
      plot.tag = element_text(size = 12),
      plot.title = element_text(size = 13, hjust = 0.1 , margin = margin(t = 10, b = -20)),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 8),
      strip.text = element_text(size = 12),
      strip.background = element_rect(color = NA))
```


# A4 

```{r, echo=FALSE, fig.width=12, fig.height=8, results='hide'}
res = lapply(1:3, function(i) readRDS(paste0("results/a_4_sp_",i,"_.RDS")))
data =
  lapply(1:3, function(i) {
  df = as.data.frame(do.call(rbind, asplit(res[[i]], 1)))
  df$algorithm = c("MAR", "BRT", "RF", "Random", "Zero")
  df$iter = sort(rep(1:20, 5))
  data = df %>% pivot_longer(cols = c(rmse_p, rmse_b, correlation_p, correlation_b))
  data$species = c(5, 10, 20)[i]
  data$type = rep(c("Count", "Presence/absence"), 200)
  return(data)
})
data = do.call(rbind, data)
data = data %>% 
  mutate(species=as.factor(species), 
         algorithm=as.factor(algorithm))

data$name = fct_collapse(data$name, 
                         spearman = c("correlation_p", "correlation_b"),
                         'log(rmse)' = c("rmse_p", "rmse_b"))

data$value[data$name == "log(rmse)"] = log(data$value[data$name == "log(rmse)"]+1)

data %>% 
  ggplot(aes(x = reorder(algorithm,rep(1:5, 240), na.rm=TRUE), y = value, fill=species)) +
  geom_boxplot() +
  theme_bw() + 
  labs(x = "Algorithm") +
  facet_grid(name~type, scale="free") +
     theme(
      plot.tag = element_text(size = 12),
      plot.title = element_text(size = 13, hjust = 0.1 , margin = margin(t = 10, b = -20)),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 8),
      strip.text = element_text(size = 12),
      strip.background = element_rect(color = NA))
```


# A5

```{r, echo=FALSE, fig.width=7, fig.height=8, results='hide'}
res = lapply(1:3, function(i) readRDS(paste0("results/a_5_sp_",i,"_.RDS")))

data =
  lapply(1:3, function(i) {
  df = as.data.frame(do.call(rbind, asplit(res[[i]], 1)))
  df$algorithm = c("MAR", "BRT", "RF", "Random", "Zero")
  df$iter = sort(rep(1:20, 5))
  data = df %>% pivot_longer(cols = c(rmse_p, rmse_b, correlation_p, correlation_b))
  data$species = c(5, 10, 20)[i]
  data$type = rep(c("Count", "Presence/absence"), 200)
  return(data)
})
data = do.call(rbind, data)
data = data %>% 
  mutate(species=as.factor(species), 
         algorithm=as.factor(algorithm))

data$name = fct_collapse(data$name, 
                         spearman = c("correlation_p", "correlation_b"),
                         'log(rmse)' = c("rmse_p", "rmse_b"))

data$value[data$name == "log(rmse)"] = log(data$value[data$name == "log(rmse)"]+1)
data = data %>% filter(name != "spearman")

data %>% 
  ggplot(aes(x = algorithm, y = value, fill=species)) +
  geom_boxplot() +
  theme_bw() + 
  labs(x = "Algorithm", y = "spearman") +
  facet_grid(name~type, scale="free") +
     theme(
      plot.tag = element_text(size = 12),
      plot.title = element_text(size = 13, hjust = 0.1 , margin = margin(t = 10, b = -20)),
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 8),
      strip.text = element_text(size = 12),
      strip.background = element_rect(color = NA))

```

